name: Trunk actions auth (staging)

on: pull_request

jobs:
  merge-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/merge-action@0da8908bc1ac50941e18217f429888367ac1be4c
        with:
          auth: github-actions
          trunk-api-url: https://api.trunk-staging.io/v2
          bazel-workspace-path: ${{ github.workspace }}/bazel
          impact-all-filters-path: .github/impact-all.yaml
          verbose: "true"

  bazel-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/bazel-action@18a780cb57161377df8647bf35346cdd15ad048b
        with:
          auth: github-actions
          trunk-api-url: https://api.trunk-staging.io/v2
          upload-targets: "true"
          test-targets: "false"
          bazel-workspace-path: ${{ github.workspace }}/bazel
          impact-all-filters-path: .github/impact-all.yaml
          verbose: "true"

  nx-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: trunk-io/nx-action@5240f99bb5e86da943b206c6bd2c8bdab2419a7f
        with:
          auth: github-actions
          trunk-api-url: https://api.trunk-staging.io/v2
          workspace-path: nx
          impact-all-filters-path: .github/impact-all.yaml
          verbose: "true"
